/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hyperskill.tictactoe;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Game obj = new Game();
        obj.startGame();
    }
}
